export const KEY_TO_RU_MAPPING = {
  q: 'я',
  w: 'ш',
  e: 'е',
  r: 'р',
  t: 'т',
  y: 'ы',
  u: 'у',
  i: 'и',
  o: 'о',
  p: 'п',
  a: 'а',
  s: 'с',
  d: 'д',
  f: 'ф',
  g: 'г',
  h: 'ч',
  j: 'й',
  k: 'к',
  l: 'л',
  z: 'з',
  x: 'х',
  c: 'ц',
  v: 'в',
  b: 'б',
  n: 'н',
  m: 'м',
  ',': ',',
  '.': '.',
  '/': '/',
  ';': ';',
  "'": "'",
  '-': '-',
  '=': '=',
  '`': '`',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  '0': '0',
}

export const LAYOUT = {
  rows: [
    [
      { key: '`', base: '`', shift: '~', alt: '~', altShift: '~' },
      { key: '1', base: '!', shift: '!', alt: '1', altShift: '~' },
      { key: '2', base: '@', shift: '@', alt: '2', altShift: '' },
      { key: '3', base: '#', shift: '#', alt: '3', altShift: '' },
      { key: '4', base: '$', shift: '$', alt: '4', altShift: '' },
      { key: '5', base: '%', shift: '%', alt: '5', altShift: '' },
      { key: '6', base: '^', shift: '^', alt: '6', altShift: '' },
      { key: '7', base: '&', shift: '&', alt: '7', altShift: '' },
      { key: '8', base: '*', shift: '*', alt: '8', altShift: '' },
      { key: '9', base: '(', shift: '(', alt: '9', altShift: '' },
      { key: "0", base: ")", shift: ')', alt: "0", altShift: '' },
      { key: "-", base: "-", shift: '_', alt: "—", altShift: '' },
      { key: "=", base: "=", shift: '+', alt: '', altShift: '' }
    ],
    [
      { key: 'q', base: 'я', shift: '', alt: 'ё', altShift: '' },
      { key: 'g', base: 'г', shift: '', alt: '6', altShift: '6' },
      { key: 'm', base: 'м', shift: '', alt: '', altShift: '' },
      { key: 'l', base: 'л', shift: '', alt: '', altShift: '' },
      { key: 'w', base: 'ш', shift: '', alt: 'щ', altShift: '' },
      { key: 'y', base: 'ы', shift: '', alt: '9', altShift: '9' },
      { key: 'f', base: 'ф', shift: '', alt: '', altShift: '' },
      { key: 'u', base: 'у', shift: '', alt: 'ю', altShift: '' },
      { key: 'b', base: 'б', shift: '', alt: '8', altShift: '8' },
      { key: "'", base: "'", shift: '"', alt: '', altShift: '' }
    ],
    [
      { key: 'd', base: 'д', shift: '', alt: '', altShift: '', homeRow: true },
      { key: 's', base: 'с', shift: '', alt: '5', altShift: '5', homeRow: true },
      { key: 't', base: 'т', shift: '', alt: '7', altShift: '7', homeRow: true },
      { key: 'n', base: 'н', shift: '', alt: 'ь', altShift: '', homeRow: true },
      { key: 'r', base: 'р', shift: '', alt: 'ъ', altShift: '', homeRow: true },
      { key: 'i', base: 'и', shift: '', alt: '1', altShift: '1', homeRow: true },
      { key: 'a', base: 'а', shift: '', alt: 'э', altShift: '', homeRow: true },
      { key: 'e', base: 'е', shift: '', alt: '3', altShift: '', homeRow: true },
      { key: 'o', base: 'о', shift: '', alt: '0', altShift: '0', homeRow: true },
      { key: 'h', base: 'ч', shift: '', alt: '4', altShift: '4', homeRow: true },
      { key: ';', base: ';', shift: ':', alt: '', altShift: '', homeRow: true }
    ],
    [
      { key: 'z', base: 'з', shift: '', alt: '2', altShift: '2' },
      { key: 'x', base: 'х', shift: '', alt: 'ж', altShift: '' },
      { key: 'c', base: 'ц', shift: '', alt: '', altShift: '' },
      { key: 'v', base: 'в', shift: '', alt: '', altShift: '' },
      { key: 'j', base: 'й', shift: '', alt: '9', altShift: '9' },
      { key: 'k', base: 'к', shift: '', alt: '', altShift: '' },
      { key: 'p', base: 'п', shift: '', alt: '', altShift: '' },
      { key: ',', base: ',', shift: '<', alt: '«', altShift: '«' },
      { key: '.', base: '.', shift: '>', alt: '»', altShift: '»' },
      { key: '/', base: '/', shift: '?', alt: '', altShift: '' }
    ]
  ]
};